title: Baidu Engineering
name: 百度LAMP技术
email: reeze.xia@gmail.com
baseurl: ""
permalink: pretty
url: "http://lamp.baidu.com"
twitter_username: reeze_xia
github_username:  baidu-lamp

paginate: 8
paginate_path: "articles/page/:num/"

duoshuo_id: baidu-lamp
disqus_id: baidu-lamp

markdown: redcarpet
redcarpet:
  extensions: ["table", "autolink"]

post_defaults:
  layout: post
  lang: cn
  has_en: false
  page_id: post

collections:
  projects:
    output: false
    permalink: /opensource/:path/
  slides:
    output: true
    permalink: /slides/:path/
  hhvm:
    output: true
    permalink: /hhvm/:path/
  authors:
    output: true
    permalink: /author/:path/
