# Site settings
title: Baidu Engineering
email: reeze.xia@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog/
permalink: pretty
url: "http://lamp.baidu.com" # the base hostname & protocol for your site
twitter_username: reeze_xia
github_username:  baidu-lamp

duoshuo_id: baidu-lamp
disqus_id: baidu-lamp

# Build settings
markdown: kramdown
